name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: ./.github/actions/setup
      with:
        node-version: 18.x
    - name: Build
      run: npm run build
    - name: Lint
      run: npm run lint
    - name: Cover
      run: npm run cover
    - name: Codecov
      uses: codecov/codecov-action@v1.0.14
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    - name: Canary
      run: npm run publisher:publish-canary
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
