name: Coverage
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: ./.github/actions/setup
    - run: npm run build
    - run: npm run cover
    - name: Codecov
      uses: codecov/codecov-action@v1.0.14
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    - name: Canary
      run: npm run publisher:canary -- dry=false
      with:
        NPM_TOKEN: ${{secrets.NPM_TOKEN}}
