# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - name: "Set r/w permissions"
      run: sudo chmod -R 777 /home/runner/work/modules
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm set unsafe-perm true
    - run: npm ci
    - run: npm build
    - run: npm run task:setup
    - run: npm test
    - run: npm task:publish -- -t ${{ secrets.NPM_AUTH_TOKEN }} -c development
